//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class matric_newEntities : DbContext
    {
        public matric_newEntities()
            : base("name=matric_newEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblbiodata> tblbiodatas { get; set; }
        public virtual DbSet<tblBioDataInter_From14> tblBioDataInter_From14 { get; set; }
        public virtual DbSet<tblBiodataInter_HE> tblBiodataInter_HE { get; set; }
        public virtual DbSet<tblBoard> tblBoards { get; set; }
        public virtual DbSet<TblCategory> TblCategories { get; set; }
        public virtual DbSet<tblcentre> tblcentres { get; set; }
        public virtual DbSet<tblChildNode> tblChildNodes { get; set; }
        public virtual DbSet<tbldatesheetinter> tbldatesheetinters { get; set; }
        public virtual DbSet<tbldatesheetmatric> tbldatesheetmatrics { get; set; }
        public virtual DbSet<tblDistrict> tblDistricts { get; set; }
        public virtual DbSet<tblHistory> tblHistories { get; set; }
        public virtual DbSet<tblInstitutes_all> tblInstitutes_all { get; set; }
        public virtual DbSet<tblParentNode> tblParentNodes { get; set; }
        public virtual DbSet<tblPicPath> tblPicPaths { get; set; }
        public virtual DbSet<tblScanned_Data> tblScanned_Data { get; set; }
        public virtual DbSet<tblBindAllotment> tblBindAllotments { get; set; }
        public virtual DbSet<tblBundle> tblBundles { get; set; }
        public virtual DbSet<tblhistoryForm16> tblhistoryForm16 { get; set; }
        public virtual DbSet<tblTehsil> tblTehsils { get; set; }
        public virtual DbSet<tblZone> tblZones { get; set; }
    }
}
