//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MiscDbEntities : DbContext
    {
        public MiscDbEntities()
            : base("name=MiscDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblemployee> tblemployees { get; set; }
        public virtual DbSet<tblEntrySlip> tblEntrySlips { get; set; }
        public virtual DbSet<tblFile> tblFiles { get; set; }
        public virtual DbSet<tblfileTrack> tblfileTracks { get; set; }
        public virtual DbSet<tblroll> tblrolls { get; set; }
        public virtual DbSet<tblwebform> tblwebforms { get; set; }
        public virtual DbSet<tblWebRight> tblWebRights { get; set; }
    }
}
