//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBiodataInter_HE
    {
        public int rno { get; set; }
        public byte @class { get; set; }
        public short Iyear { get; set; }
        public byte sess { get; set; }
        public string strRegNo { get; set; }
        public Nullable<byte> schm { get; set; }
        public Nullable<int> oldRno { get; set; }
        public Nullable<short> YearOfLastAp { get; set; }
        public Nullable<byte> SessOfLastAp { get; set; }
        public Nullable<byte> IntBrd_cd { get; set; }
        public Nullable<int> matRno { get; set; }
        public Nullable<short> yearOfPass { get; set; }
        public Nullable<byte> sessOfPass { get; set; }
        public Nullable<byte> Brd_cd { get; set; }
        public Nullable<int> classRno { get; set; }
        public string CollGrade { get; set; }
        public string name { get; set; }
        public string Fname { get; set; }
        public string addr { get; set; }
        public string BForm { get; set; }
        public string FNIC { get; set; }
        public string markOfIden { get; set; }
        public Nullable<byte> rel { get; set; }
        public Nullable<byte> regPvt { get; set; }
        public Nullable<byte> sex { get; set; }
        public Nullable<byte> med { get; set; }
        public Nullable<byte> nat { get; set; }
        public Nullable<byte> ruralOrurban { get; set; }
        public Nullable<byte> dist_cd { get; set; }
        public Nullable<byte> teh_cd { get; set; }
        public string FormNo { get; set; }
        public Nullable<byte> cat11 { get; set; }
        public Nullable<byte> cat12 { get; set; }
        public Nullable<short> cent_cd { get; set; }
        public Nullable<byte> exgrp { get; set; }
        public Nullable<byte> grp_cd { get; set; }
        public Nullable<int> coll_cd { get; set; }
        public Nullable<byte> sub1 { get; set; }
        public Nullable<byte> sub1Ap1 { get; set; }
        public Nullable<byte> sub1mt1 { get; set; }
        public Nullable<byte> sub1st1 { get; set; }
        public Nullable<byte> sub1pf1 { get; set; }
        public Nullable<byte> sub1Ap2 { get; set; }
        public Nullable<byte> sub1mt2 { get; set; }
        public Nullable<byte> sub1St2 { get; set; }
        public Nullable<byte> sub1Pf2 { get; set; }
        public Nullable<byte> sub2 { get; set; }
        public Nullable<byte> sub2Ap1 { get; set; }
        public Nullable<byte> sub2mt1 { get; set; }
        public Nullable<byte> sub2st1 { get; set; }
        public Nullable<byte> sub2pf1 { get; set; }
        public Nullable<byte> sub2Ap2 { get; set; }
        public Nullable<byte> sub2mt2 { get; set; }
        public Nullable<byte> sub2st2 { get; set; }
        public Nullable<byte> sub2pf2 { get; set; }
        public Nullable<byte> sub3 { get; set; }
        public Nullable<byte> sub3Ap1 { get; set; }
        public Nullable<byte> sub3mt1 { get; set; }
        public Nullable<byte> sub3st1 { get; set; }
        public Nullable<byte> sub3pf1 { get; set; }
        public Nullable<byte> sub4 { get; set; }
        public Nullable<byte> sub4A { get; set; }
        public Nullable<byte> sub4Ap1 { get; set; }
        public Nullable<byte> sub4mt1 { get; set; }
        public Nullable<byte> sub4st1 { get; set; }
        public Nullable<byte> sub4mp1 { get; set; }
        public Nullable<byte> Sub4sp1 { get; set; }
        public Nullable<byte> Sub4prpf1 { get; set; }
        public Nullable<byte> sub4pf1 { get; set; }
        public Nullable<byte> sub4Ap2 { get; set; }
        public Nullable<byte> sub4mt2 { get; set; }
        public Nullable<byte> sub4st2 { get; set; }
        public Nullable<byte> sub4mp2 { get; set; }
        public Nullable<byte> sub4sp2 { get; set; }
        public Nullable<byte> sub4pf2 { get; set; }
        public Nullable<byte> sub4prpf2 { get; set; }
        public Nullable<byte> sub5 { get; set; }
        public Nullable<byte> sub5A { get; set; }
        public Nullable<byte> sub5Ap1 { get; set; }
        public Nullable<byte> sub5mt1 { get; set; }
        public Nullable<byte> sub5st1 { get; set; }
        public Nullable<byte> sub5mp1 { get; set; }
        public Nullable<byte> sub5sp1 { get; set; }
        public Nullable<byte> sub5prpf1 { get; set; }
        public Nullable<byte> sub5pf1 { get; set; }
        public Nullable<byte> sub5Ap2 { get; set; }
        public Nullable<byte> sub5mt2 { get; set; }
        public Nullable<byte> sub5st2 { get; set; }
        public Nullable<byte> sub5mp2 { get; set; }
        public Nullable<byte> sub5sp2 { get; set; }
        public Nullable<byte> sub5pf2 { get; set; }
        public Nullable<byte> sub5prpf2 { get; set; }
        public Nullable<byte> sub6 { get; set; }
        public Nullable<byte> sub6A { get; set; }
        public Nullable<byte> sub6Ap1 { get; set; }
        public Nullable<byte> sub6mt1 { get; set; }
        public Nullable<byte> sub6st1 { get; set; }
        public Nullable<byte> Sub6mp1 { get; set; }
        public Nullable<byte> sub6sp1 { get; set; }
        public Nullable<byte> sub6prpf1 { get; set; }
        public Nullable<byte> sub6pf1 { get; set; }
        public Nullable<byte> sub6Ap2 { get; set; }
        public Nullable<byte> sub6mt2 { get; set; }
        public Nullable<byte> sub6st2 { get; set; }
        public Nullable<byte> sub6mp2 { get; set; }
        public Nullable<byte> sub6sp2 { get; set; }
        public Nullable<byte> sub6pf2 { get; set; }
        public Nullable<byte> sub6prpf2 { get; set; }
        public Nullable<byte> sub7 { get; set; }
        public Nullable<byte> sub7A { get; set; }
        public Nullable<byte> sub7Ap1 { get; set; }
        public Nullable<byte> sub7mt1 { get; set; }
        public Nullable<byte> sub7st1 { get; set; }
        public Nullable<byte> sub7pf1 { get; set; }
        public Nullable<byte> sub7Ap2 { get; set; }
        public Nullable<byte> sub7mt2 { get; set; }
        public Nullable<byte> sub7st2 { get; set; }
        public Nullable<byte> sub7mp2 { get; set; }
        public Nullable<byte> sub7sp2 { get; set; }
        public Nullable<byte> sub7pf2 { get; set; }
        public Nullable<byte> sub7prpf { get; set; }
        public Nullable<byte> sub8 { get; set; }
        public Nullable<byte> sub8Ap2 { get; set; }
        public Nullable<byte> sub8mt2 { get; set; }
        public Nullable<byte> sub8st2 { get; set; }
        public Nullable<byte> sub8pf2 { get; set; }
        public Nullable<short> obt_mrk { get; set; }
        public string result1 { get; set; }
        public string result2 { get; set; }
        public Nullable<byte> status { get; set; }
        public Nullable<byte> spl_cd { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public string ekpo { get; set; }
        public string ckpo { get; set; }
        public Nullable<System.DateTime> cDate { get; set; }
        public Nullable<byte> Pic { get; set; }
        public Nullable<byte> sn { get; set; }
        public Nullable<byte> chance { get; set; }
        public Nullable<int> zone_cd { get; set; }
        public string MobNo { get; set; }
        public Nullable<int> Emp_cd { get; set; }
        public Nullable<byte> mi_type { get; set; }
        public Nullable<int> Emp_Rslt { get; set; }
        public Nullable<int> BindNo { get; set; }
        public Nullable<int> SrNo { get; set; }
        public Nullable<byte> frm { get; set; }
    }
}
