//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBundle
    {
        public int myear { get; set; }
        public byte sess { get; set; }
        public byte @class { get; set; }
        public Nullable<int> orderBy { get; set; }
        public byte mExchange { get; set; }
        public byte Sub_cd { get; set; }
        public byte ExGrp { get; set; }
        public int start { get; set; }
        public int ended { get; set; }
        public Nullable<int> BundleNo { get; set; }
        public Nullable<int> frCmp { get; set; }
        public Nullable<int> isDeaf { get; set; }
        public Nullable<byte> schm { get; set; }
    }
}
