//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBoard
    {
        public int Brd_cd { get; set; }
        public string Brd_name { get; set; }
        public string Brd_Abr { get; set; }
        public string pitb_abre { get; set; }
    }
}
