//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcentre
    {
        public short CENT_CD { get; set; }
        public short mYear { get; set; }
        public byte sess { get; set; }
        public byte @class { get; set; }
        public string CENT_NAME { get; set; }
        public string Cent_Abre { get; set; }
        public Nullable<int> dist_cd { get; set; }
        public Nullable<byte> cent_Gen { get; set; }
        public Nullable<int> Zone_cd { get; set; }
        public Nullable<int> Teh_cd { get; set; }
        public Nullable<int> Max1st_P2 { get; set; }
        public Nullable<int> Max2nd_P2 { get; set; }
        public Nullable<int> Max1st_P1 { get; set; }
        public Nullable<int> Max2nd_P1 { get; set; }
        public Nullable<int> oMax { get; set; }
        public Nullable<int> Inst_cd { get; set; }
        public Nullable<bool> onlyP1 { get; set; }
        public Nullable<byte> cent_inst_gen { get; set; }
        public string Bank_Name { get; set; }
        public Nullable<int> zone_cd2 { get; set; }
        public Nullable<int> cent_opt { get; set; }
        public Nullable<int> cent_opt_girls { get; set; }
        public Nullable<int> cent_cd_new { get; set; }
        public Nullable<int> Cent_cd_Old { get; set; }
        public Nullable<int> Bank_Code { get; set; }
        public Nullable<bool> DeafOnly { get; set; }
    }
}
