//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblChildNode
    {
        public int ChildNodeID { get; set; }
        public string ChildNodeName { get; set; }
        public Nullable<int> NodeType { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isCommon { get; set; }
        public string formUrl { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
        public Nullable<int> ParentNodeID { get; set; }
    
        public virtual tblParentNode tblParentNode { get; set; }
    }
}
