//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldatesheetinter
    {
        public byte sub_cd { get; set; }
        public int IYEAR { get; set; }
        public int sess { get; set; }
        public byte @class { get; set; }
        public string sub_Name { get; set; }
        public string Date1 { get; set; }
        public Nullable<byte> Subgrp1 { get; set; }
        public string date2 { get; set; }
        public Nullable<byte> subgrp2 { get; set; }
    }
}
