//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbldatesheetmatric
    {
        public short IYear { get; set; }
        public byte Sess { get; set; }
        public byte Class { get; set; }
        public byte SUB_CD { get; set; }
        public string SUB_ABR { get; set; }
        public string SUB_NAME { get; set; }
        public Nullable<byte> TH1_MRK { get; set; }
        public Nullable<byte> TH2_MRK { get; set; }
        public Nullable<byte> PR_MRK { get; set; }
        public Nullable<byte> TH1_PASSMRK { get; set; }
        public Nullable<byte> TH2_PASSMRK { get; set; }
        public Nullable<byte> SUB_TOTPASSMRK { get; set; }
        public Nullable<byte> PR2_PASSMRK { get; set; }
        public Nullable<byte> PR { get; set; }
        public Nullable<byte> SUB_SEX { get; set; }
        public string DATE1 { get; set; }
        public Nullable<byte> SUBGRP1 { get; set; }
        public string DATE2 { get; set; }
        public Nullable<byte> SUBGRP2 { get; set; }
        public string cgtime { get; set; }
        public string sgrp { get; set; }
    }
}
