//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntrySlip
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string FName { get; set; }
        public Nullable<byte> sex { get; set; }
        public string cnic { get; set; }
        public Nullable<int> rno { get; set; }
        public Nullable<int> @class { get; set; }
        public Nullable<int> sess { get; set; }
        public Nullable<int> iyear { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> eUser { get; set; }
        public Nullable<int> branch { get; set; }
        public Nullable<int> NoOfPersons { get; set; }
    }
}
