//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblemployee
    {
        public int emp_cd { get; set; }
        public string pass { get; set; }
        public string Name { get; set; }
        public string fname { get; set; }
        public string cnic { get; set; }
        public string ntn { get; set; }
        public Nullable<System.DateTime> dob { get; set; }
        public Nullable<byte> religion { get; set; }
        public string address { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> last_qualify { get; set; }
        public Nullable<byte> gender { get; set; }
        public Nullable<System.DateTime> date_joining { get; set; }
        public Nullable<System.DateTime> date_promote { get; set; }
        public Nullable<System.DateTime> date_retired { get; set; }
        public Nullable<byte> seniority { get; set; }
        public Nullable<int> Branch_Code { get; set; }
        public Nullable<byte> emp_status { get; set; }
        public Nullable<byte> bill_category { get; set; }
        public Nullable<byte> emp_cat { get; set; }
        public Nullable<byte> bs { get; set; }
        public Nullable<byte> desig { get; set; }
        public Nullable<byte> salary_type { get; set; }
        public Nullable<int> ecr { get; set; }
        public string blood_grp { get; set; }
        public string email { get; set; }
        public Nullable<byte> Disability { get; set; }
        public string Driving_License { get; set; }
        public Nullable<System.DateTime> Expiry_Date { get; set; }
        public Nullable<byte> roll_id { get; set; }
        public Nullable<bool> isActive { get; set; }
        public Nullable<bool> isSuperAdmin { get; set; }
        public string accountNo { get; set; }
        public Nullable<byte> pay_stage { get; set; }
        public Nullable<int> br_sec { get; set; }
        public string about { get; set; }
        public byte[] image { get; set; }
        public Nullable<byte> hajj { get; set; }
        public Nullable<byte> umrah { get; set; }
        public string OutDoorJob { get; set; }
    }
}
