//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblFile
    {
        public int fileId { get; set; }
        public string fileDesc { get; set; }
        public Nullable<int> br_code { get; set; }
        public string SubmittedBy { get; set; }
        public string SubmitterMobNo { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<int> next_br_code { get; set; }
        public Nullable<int> isDeleted { get; set; }
        public Nullable<byte> status { get; set; }
        public string remarks { get; set; }
        public Nullable<byte> IsSent { get; set; }
        public string RegNo { get; set; }
        public string RegDate { get; set; }
        public string RetDate { get; set; }
        public string OwoDiaryNo { get; set; }
        public string OwoDate { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> Emp_cd { get; set; }
    }
}
