//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblfileTrack
    {
        public int id { get; set; }
        public Nullable<int> fileId { get; set; }
        public Nullable<int> Br_code { get; set; }
        public string Br_FileNo { get; set; }
        public Nullable<int> ReceivedBy { get; set; }
        public Nullable<System.DateTime> recivedDate { get; set; }
        public string remarks { get; set; }
        public Nullable<int> prev_Br_code { get; set; }
        public Nullable<int> next_br_code { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<System.DateTime> transferDate { get; set; }
        public Nullable<int> transferBy { get; set; }
        public Nullable<bool> IsNext_Received { get; set; }
        public Nullable<bool> isCompleted { get; set; }
        public Nullable<int> emp_cd { get; set; }
    }
}
