//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblHistory
    {
        public int id { get; set; }
        public int rno { get; set; }
        public string formno { get; set; }
        public int myear { get; set; }
        public int sess { get; set; }
        public int @class { get; set; }
        public string histStr { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public int changedBy { get; set; }
        public Nullable<int> changedByForm { get; set; }
        public Nullable<int> CrcByEmp { get; set; }
        public string SystemIP { get; set; }
        public string SystemName { get; set; }
        public string DomainUser { get; set; }
    }
}
