//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblhistoryForm16
    {
        public string formno { get; set; }
        public Nullable<byte> @class { get; set; }
        public Nullable<short> mYear { get; set; }
        public Nullable<byte> sess { get; set; }
        public string PrevString { get; set; }
        public string ChangedString { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public Nullable<int> ChangedBy { get; set; }
        public Nullable<int> ChangedByForm { get; set; }
    }
}
