//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInstitutes_all
    {
        public Nullable<int> Inst_Id { get; set; }
        public int Inst_cd { get; set; }
        public string Inst_pwd { get; set; }
        public string Name { get; set; }
        public string address { get; set; }
        public Nullable<byte> IsActive { get; set; }
        public Nullable<byte> Gender { get; set; }
        public Nullable<byte> IsGovernment { get; set; }
        public Nullable<byte> IsRural { get; set; }
        public Nullable<byte> IsCommunity { get; set; }
        public string LandLine { get; set; }
        public string MobNo { get; set; }
        public Nullable<byte> affiliation_Grace_Period { get; set; }
        public Nullable<byte> IsExameCentre { get; set; }
        public Nullable<byte> edu_lvl { get; set; }
        public Nullable<System.DateTime> affiliation_date { get; set; }
        public Nullable<System.DateTime> expiration_date { get; set; }
        public Nullable<System.DateTime> feedingDate { get; set; }
        public Nullable<int> Kpo { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> IsDeleted { get; set; }
        public Nullable<byte> dist_cd { get; set; }
        public Nullable<short> teh_cd { get; set; }
        public string emis_code { get; set; }
        public Nullable<int> zone_cd { get; set; }
        public Nullable<int> iZone_cd { get; set; }
        public string email { get; set; }
        public Nullable<int> emp_cd { get; set; }
        public Nullable<int> pp_zone { get; set; }
        public string allowed_mGrp { get; set; }
        public string allowed_iGrp { get; set; }
        public string allowed_mSub { get; set; }
        public string allowed_iSub { get; set; }
        public string inst_Abre { get; set; }
        public string Remarks { get; set; }
    }
}
