//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPicPath
    {
        public short mYear { get; set; }
        public byte Sess { get; set; }
        public byte Class { get; set; }
        public string PicPaThRetype { get; set; }
        public string PicPaThMiss { get; set; }
        public string PicPathGar { get; set; }
        public string PicPaTh1 { get; set; }
        public string PicPath2 { get; set; }
        public string PicPath3 { get; set; }
        public string PicPaTh4 { get; set; }
        public string PicPaTh5 { get; set; }
        public string PicPaTh6 { get; set; }
        public string PicPaTh7 { get; set; }
        public string PicPaTh8 { get; set; }
        public string PicPath9 { get; set; }
        public string PicPath10 { get; set; }
        public string PicPath11 { get; set; }
        public string PicPath12 { get; set; }
        public string DateOfDeclaration { get; set; }
        public Nullable<long> pth1strt { get; set; }
        public Nullable<long> pth2strt { get; set; }
        public Nullable<long> pth3strt { get; set; }
        public Nullable<long> pth4strt { get; set; }
        public Nullable<long> pth5strt { get; set; }
        public Nullable<long> pth6Strt { get; set; }
        public Nullable<long> pth7Strt { get; set; }
        public Nullable<long> pth8Strt { get; set; }
        public Nullable<long> pth9Strt { get; set; }
        public Nullable<long> pth10Strt { get; set; }
        public Nullable<long> pth11Strt { get; set; }
        public Nullable<long> pth12Strt { get; set; }
        public byte[] img { get; set; }
        public string DecDate { get; set; }
        public string DecTime { get; set; }
    }
}
