//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParentNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblParentNode()
        {
            this.tblChildNodes = new HashSet<tblChildNode>();
        }
    
        public int ParentNodeID { get; set; }
        public string NodeName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblChildNode> tblChildNodes { get; set; }
    }
}
