//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblScanned_Data
    {
        public string formno { get; set; }
        public int Class { get; set; }
        public int iyear { get; set; }
        public int sess { get; set; }
        public int bindNo { get; set; }
        public int SrNo { get; set; }
        public string picpath { get; set; }
        public string barCode { get; set; }
        public Nullable<System.DateTime> edate { get; set; }
        public Nullable<int> ekpo { get; set; }
        public Nullable<byte> Excp { get; set; }
        public Nullable<int> emp_cd { get; set; }
    }
}
