//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblWebRight
    {
        public int id { get; set; }
        public int UserId { get; set; }
        public int formNo { get; set; }
        public int fYear { get; set; }
        public byte fSess { get; set; }
        public byte fClass { get; set; }
        public Nullable<System.DateTime> eDate { get; set; }
        public Nullable<int> eUser { get; set; }
        public Nullable<int> rightsDays { get; set; }
        public Nullable<bool> isActive { get; set; }
    }
}
