//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BISEWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblZone
    {
        public short mYear { get; set; }
        public byte Class { get; set; }
        public byte Sess { get; set; }
        public int zone_cd { get; set; }
        public string zone_name { get; set; }
        public Nullable<byte> teh_cd { get; set; }
        public Nullable<byte> Flag { get; set; }
        public Nullable<byte> Gender { get; set; }
    
        public virtual tblTehsil tblTehsil { get; set; }
        public virtual tblZone tblZones1 { get; set; }
        public virtual tblZone tblZone1 { get; set; }
    }
}
